name: callWorkFlowTest
on: push

jobs:
  my-job:
    permissions:
      contents: write
      pages: write     
      id-token: write
    uses: ejohnsontrux/actions-learning-pathway/.github/workflows/build-test-deploy.yml@main
    with:
      node-version: '18.x' 
